import { SymptomDef, ContextKey, SkinType, AxisKey, RiskPattern, MetaQuestion, Product } from "./types";

export const SYMPTOMS: Record<string, SymptomDef> = {
  // Category 1 — Breakouts & Acne
  C1_01: { id: "C1_01", text_en: "Recurring breakouts appear regularly", category: 1, weights: { acne: 0.9, seb: 0.5 } },
  C1_02: { id: "C1_02", text_en: "Breakouts concentrate on jaw, cheeks, or forehead", category: 1, weights: { acne: 0.6, sen: 0.4 } },
  C1_03: { id: "C1_03", text_en: "Skin worsens before menstruation or hormonal shifts", category: 1, weights: { acne: 0.5, sen: 0.4, seb: 0.3 } },
  C1_04: { id: "C1_04", text_en: "Breakouts appear where masks, helmets, or glasses sit", category: 1, weights: { acne: 0.6, bar: 0.4, sen: 0.3 } },
  C1_05: { id: "C1_05", text_en: "Breakouts flare after exercise or sweating", category: 1, weights: { acne: 0.5, seb: 0.5 } },
  C1_06: { id: "C1_06", text_en: "New skincare products trigger breakouts in specific areas", category: 1, weights: { sen: 0.7, acne: 0.4, bar: 0.3 } },
  C1_07: { id: "C1_07", text_en: "Hard, deep nodules form under the skin", category: 1, weights: { acne: 0.9, sen: 0.2 } },
  C1_08: { id: "C1_08", text_en: "Pus-filled inflammatory lesions appear frequently", category: 1, weights: { acne: 1.0, sen: 0.3 } },
  C1_09: { id: "C1_09", text_en: "Small bumps form in non-inflamed areas", category: 1, weights: { acne: 0.5, seb: 0.4, texture: 0.3 } },
  C1_10: { id: "C1_10", text_en: "Red marks remain for months after breakouts clear", category: 1, weights: { acne: 0.4, sen: 0.3, bar: 0.2 } },
  C1_11: { id: "C1_11", text_en: "Sebum refills immediately after extraction", category: 1, weights: { seb: 0.9, acne: 0.2 } },
  C1_12: { id: "C1_12", text_en: "Sebum production feels suddenly increased", category: 1, weights: { seb: 0.8, acne: 0.3 } },
  C1_13: { id: "C1_13", text_en: "Stress immediately triggers skin reactions", category: 1, weights: { acne: 0.5, sen: 0.5 } },
  C1_14: { id: "C1_14", text_en: "Sun exposure makes skin reactive and prone to breakouts", category: 1, weights: { acne: 0.4, ox: 0.6, sen: 0.4 } },
  C1_15: { id: "C1_15", text_en: "Body acne (back or chest) appears alongside facial acne", category: 1, weights: { acne: 0.7, seb: 0.5 } },

  // Category 2 — Oiliness & Makeup Wear
  C2_01: { id: "C2_01", text_en: "Face becomes shiny by mid-afternoon", category: 2, weights: { seb: 0.8, makeup_stability: 0.6 } },
  C2_02: { id: "C2_02", text_en: "T-zone (forehead and nose) is noticeably oilier", category: 2, weights: { seb: 0.8, makeup_stability: 0.5 } },
  C2_03: { id: "C2_03", text_en: "Sebum reappears within 2 hours of cleansing", category: 2, weights: { seb: 0.9, acne: 0.2 } },
  C2_04: { id: "C2_04", text_en: "Makeup breaks down within 3–4 hours", category: 2, weights: { makeup_stability: 0.9, seb: 0.6 } },
  C2_05: { id: "C2_05", text_en: "Foundation sinks into pores or lifts off skin", category: 2, weights: { texture: 0.7, seb: 0.5, makeup_stability: 0.5 } },
  C2_06: { id: "C2_06", text_en: "Cushion and base products slide or pill", category: 2, weights: { makeup_stability: 0.8, seb: 0.5 } },
  C2_07: { id: "C2_07", text_en: "Surface looks oily but underneath feels dry", category: 2, weights: { seb: 0.6, hyd: 0.6, bar: 0.4 } },
  C2_08: { id: "C2_08", text_en: "Excess sebum makes skin tone look dull", category: 2, weights: { seb: 0.6, pigment: 0.3, ox: 0.3 } },
  C2_09: { id: "C2_09", text_en: "Blotting powder doesn't prevent shine returning", category: 2, weights: { seb: 0.9, makeup_stability: 0.7 } },
  C2_10: { id: "C2_10", text_en: "Makeup oxidises and darkens over time", category: 2, weights: { makeup_stability: 0.7, ox: 0.4, seb: 0.4 } },
  C2_11: { id: "C2_11", text_en: "Nose and cheek area breaks down first", category: 2, weights: { seb: 0.7, makeup_stability: 0.6, texture: 0.3 } },
  C2_12: { id: "C2_12", text_en: "Blurring and primer products don't last", category: 2, weights: { makeup_stability: 0.8, seb: 0.5 } },
  C2_13: { id: "C2_13", text_en: "Oiliness is significantly worse in summer", category: 2, weights: { seb: 0.7, makeup_stability: 0.5, ox: 0.3 } },
  C2_14: { id: "C2_14", text_en: "There's a stark difference between T-zone and cheek oiliness", category: 2, weights: { seb: 0.6, hyd: 0.4, makeup_stability: 0.4 } },
  C2_15: { id: "C2_15", text_en: "Under-eye concealer creases or migrates by evening", category: 2, weights: { makeup_stability: 0.7, seb: 0.4 } },

  // Category 3 — Dryness & Dehydration
  C3_01: { id: "C3_01", text_en: "Skin feels tight immediately after cleansing", category: 3, weights: { hyd: 0.9, bar: 0.5 } },
  C3_02: { id: "C3_02", text_en: "Moisturiser only lasts 1–2 hours before skin feels dry again", category: 3, weights: { hyd: 0.8, bar: 0.7 } },
  C3_03: { id: "C3_03", text_en: "Flaky skin is visibly lifting from the surface", category: 3, weights: { hyd: 0.7, texture: 0.5, bar: 0.4 } },
  C3_04: { id: "C3_04", text_en: "Makeup flakes or cracks on skin throughout the day", category: 3, weights: { hyd: 0.7, makeup_stability: 0.6, bar: 0.3 } },
  C3_05: { id: "C3_05", text_en: "Skin looks dull and lacklustre overall", category: 3, weights: { hyd: 0.8, aging: 0.3 } },
  C3_06: { id: "C3_06", text_en: "Fine lines become more pronounced when skin is dry", category: 3, weights: { hyd: 0.6, aging: 0.5 } },
  C3_07: { id: "C3_07", text_en: "Eye and lip contour areas feel especially dry", category: 3, weights: { hyd: 0.7, aging: 0.4, bar: 0.3 } },
  C3_08: { id: "C3_08", text_en: "Lip contour frequently cracks", category: 3, weights: { hyd: 0.8, bar: 0.4 } },
  C3_09: { id: "C3_09", text_en: "Dryness worsens significantly in winter, AC or heated rooms", category: 3, weights: { hyd: 0.7, bar: 0.4, sen: 0.2 } },
  C3_10: { id: "C3_10", text_en: "Sheet masks provide only temporary relief", category: 3, weights: { hyd: 0.7, bar: 0.6 } },
  C3_11: { id: "C3_11", text_en: "Skin feels stiff and constricted first thing in the morning", category: 3, weights: { hyd: 0.8, bar: 0.4 } },
  C3_12: { id: "C3_12", text_en: "Multiple layers of moisture products are needed to feel comfortable", category: 3, weights: { hyd: 0.6, bar: 0.6 } },
  C3_13: { id: "C3_13", text_en: "Skin loses moisture rapidly after application", category: 3, weights: { hyd: 0.7, bar: 0.6 } },
  C3_14: { id: "C3_14", text_en: "Skin looks thin and superficial capillaries are visible", category: 3, weights: { bar: 0.6, hyd: 0.5, sen: 0.4 } },
  C3_15: { id: "C3_15", text_en: "Skin noticeably tightens in dry environments (flights, etc.)", category: 3, weights: { hyd: 0.7, bar: 0.3 } },

  // Category 4 — Sensitivity & Redness
  C4_01: { id: "C4_01", text_en: "Skin flushes easily", category: 4, weights: { sen: 0.8, bar: 0.5 } },
  C4_02: { id: "C4_02", text_en: "Face becomes red after cleansing", category: 4, weights: { sen: 0.8, bar: 0.6 } },
  C4_03: { id: "C4_03", text_en: "Skin stings or burns", category: 4, weights: { sen: 0.9, bar: 0.5 } },
  C4_04: { id: "C4_04", text_en: "Exfoliation causes prolonged irritation", category: 4, weights: { sen: 0.7, bar: 0.7 } },
  C4_05: { id: "C4_05", text_en: "Acid-based actives (AHA/BHA/Vitamin C) cause stinging", category: 4, weights: { sen: 0.8, bar: 0.5 } },
  C4_06: { id: "C4_06", text_en: "Retinol causes significant peeling or irritation", category: 4, weights: { sen: 0.7, bar: 0.6 } },
  C4_07: { id: "C4_07", text_en: "Skin reacts to temperature changes", category: 4, weights: { sen: 0.7, bar: 0.4 } },
  C4_08: { id: "C4_08", text_en: "Cold weather immediately causes redness", category: 4, weights: { sen: 0.7, bar: 0.4 } },
  C4_09: { id: "C4_09", text_en: "Flushing after heat or exercise persists for over 30 minutes", category: 4, weights: { sen: 0.7, ox: 0.3 } },
  C4_10: { id: "C4_10", text_en: "Stress visibly reddens the skin", category: 4, weights: { sen: 0.7, bar: 0.3 } },
  C4_11: { id: "C4_11", text_en: "Trying a new product feels risky", category: 4, weights: { sen: 0.6, bar: 0.5 } },
  C4_12: { id: "C4_12", text_en: "Fragrance and alcohol-based products cause reactions", category: 4, weights: { sen: 0.8, bar: 0.5 } },
  C4_13: { id: "C4_13", text_en: "Skin itches frequently", category: 4, weights: { sen: 0.7, bar: 0.6 } },
  C4_14: { id: "C4_14", text_en: "Redness and dryness appear simultaneously", category: 4, weights: { sen: 0.6, bar: 0.7, hyd: 0.5 } },
  C4_15: { id: "C4_15", text_en: "Visible red capillaries appear on cheeks or nose", category: 4, weights: { sen: 0.7, aging: 0.3, bar: 0.4 } },

  // Category 5 — Pigmentation & Skintone
  C5_01: { id: "C5_01", text_en: "Spots and blemishes are gradually darkening", category: 5, weights: { pigment: 0.9, ox: 0.4 } },
  C5_02: { id: "C5_02", text_en: "Melasma (hormonally driven pigmentation) is present", category: 5, weights: { pigment: 0.9, ox: 0.5 } },
  C5_03: { id: "C5_03", text_en: "Post-acne dark marks (PIH) persist for months", category: 5, weights: { pigment: 0.8, acne: 0.2 } },
  C5_04: { id: "C5_04", text_en: "Skin tone is uneven", category: 5, weights: { pigment: 0.8, texture: 0.3 } },
  C5_05: { id: "C5_05", text_en: "Complexion looks dull and lacks radiance", category: 5, weights: { pigment: 0.7, ox: 0.6 } },
  C5_06: { id: "C5_06", text_en: "Colour deepens quickly after sun exposure", category: 5, weights: { pigment: 0.8, ox: 0.7 } },
  C5_07: { id: "C5_07", text_en: "The area beside the nose or around the mouth appears darker", category: 5, weights: { pigment: 0.6, texture: 0.3 } },
  C5_08: { id: "C5_08", text_en: "Dark circles have a brownish tone (melanin-type)", category: 5, weights: { pigment: 0.6, aging: 0.2 } },
  C5_09: { id: "C5_09", text_en: "Skin has an oxidised or grey cast", category: 5, weights: { pigment: 0.4, ox: 0.7, hyd: 0.3 } },
  C5_10: { id: "C5_10", text_en: "Skin looks flat and lifeless even with makeup", category: 5, weights: { pigment: 0.5, ox: 0.5, hyd: 0.4 } },
  C5_11: { id: "C5_11", text_en: "Neck and face are noticeably different in tone", category: 5, weights: { pigment: 0.7, ox: 0.4 } },
  C5_12: { id: "C5_12", text_en: "Central face zone (nose, cheeks) appears flushed or darker", category: 5, weights: { pigment: 0.6, sen: 0.3 } },
  C5_13: { id: "C5_13", text_en: "Spots and pigmentation are visibly increasing over time", category: 5, weights: { pigment: 0.8, ox: 0.5, aging: 0.3 } },
  C5_14: { id: "C5_14", text_en: "Pigmentation worsened during pregnancy or with hormonal medication", category: 5, weights: { pigment: 0.8, ox: 0.3 } },
  C5_15: { id: "C5_15", text_en: "Skin tans faster and more intensely than others in the same conditions", category: 5, weights: { pigment: 0.7, ox: 0.5 } },

  // Category 6 — Pores & Texture
  C6_01: { id: "C6_01", text_en: "Pores appear enlarged overall", category: 6, weights: { texture: 0.8, seb: 0.5 } },
  C6_02: { id: "C6_02", text_en: "Nose pores are particularly enlarged and visible", category: 6, weights: { texture: 0.8, seb: 0.6 } },
  C6_03: { id: "C6_03", text_en: "Cheek pores appear stretched vertically (sagging pores)", category: 6, weights: { texture: 0.7, aging: 0.5 } },
  C6_04: { id: "C6_04", text_en: "Pores look dark or blocked with oxidised sebum", category: 6, weights: { seb: 0.7, texture: 0.7, acne: 0.2 } },
  C6_05: { id: "C6_05", text_en: "Cream and foundation seem to 'disappear' into pores", category: 6, weights: { texture: 0.7, seb: 0.5, makeup_stability: 0.5 } },
  C6_06: { id: "C6_06", text_en: "Skin surface feels rough", category: 6, weights: { texture: 0.9, hyd: 0.3 } },
  C6_07: { id: "C6_07", text_en: "Skin surface is bumpy and uneven", category: 6, weights: { texture: 0.9, acne: 0.3 } },
  C6_08: { id: "C6_08", text_en: "Unevenness is visible from the side profile", category: 6, weights: { texture: 0.8 } },
  C6_09: { id: "C6_09", text_en: "Skin feels like there is a build-up of dead cells", category: 6, weights: { texture: 0.7, hyd: 0.4, bar: 0.3 } },
  C6_10: { id: "C6_10", text_en: "Skin texture shows clearly in photos", category: 6, weights: { texture: 0.8 } },
  C6_11: { id: "C6_11", text_en: "Skin doesn't look clean even after cleansing", category: 6, weights: { texture: 0.6, seb: 0.5, acne: 0.3 } },
  C6_12: { id: "C6_12", text_en: "Solidified sebum feels lodged inside pores", category: 6, weights: { seb: 0.7, texture: 0.6 } },
  C6_13: { id: "C6_13", text_en: "Lighting accentuates skin texture and unevenness", category: 6, weights: { texture: 0.8 } },
  C6_14: { id: "C6_14", text_en: "Pores become more visible after applying foundation", category: 6, weights: { texture: 0.7, seb: 0.4, makeup_stability: 0.4 } },
  C6_15: { id: "C6_15", text_en: "Skin was once smoother — texture has noticeably worsened", category: 6, weights: { texture: 0.7, bar: 0.4, aging: 0.3 } },

  // Category 7 — Wrinkles & Firmness
  C7_01: { id: "C7_01", text_en: "Fine lines around the eyes have increased", category: 7, weights: { aging: 0.8, hyd: 0.3 } },
  C7_02: { id: "C7_02", text_en: "Expression lines are deep when smiling", category: 7, weights: { aging: 0.8 } },
  C7_03: { id: "C7_03", text_en: "Nasolabial folds and lip lines are deepening", category: 7, weights: { aging: 0.9 } },
  C7_04: { id: "C7_04", text_en: "Neck lines are forming", category: 7, weights: { aging: 0.7 } },
  C7_05: { id: "C7_05", text_en: "Jawline definition is softening", category: 7, weights: { aging: 0.8 } },
  C7_06: { id: "C7_06", text_en: "Skin firmness is noticeably reduced", category: 7, weights: { aging: 0.9, hyd: 0.3 } },
  C7_07: { id: "C7_07", text_en: "Skin sags easily and lacks structural support", category: 7, weights: { aging: 0.9 } },
  C7_08: { id: "C7_08", text_en: "Skin is thinning alongside loss of elasticity", category: 7, weights: { aging: 0.7, bar: 0.4 } },
  C7_09: { id: "C7_09", text_en: "Pore size seems to be increasing as skin loses firmness", category: 7, weights: { aging: 0.6, texture: 0.5 } },
  C7_10: { id: "C7_10", text_en: "Makeup settles into wrinkles throughout the day", category: 7, weights: { aging: 0.6, hyd: 0.4, makeup_stability: 0.4 } },
  C7_11: { id: "C7_11", text_en: "Skin is measurably less plump than before", category: 7, weights: { aging: 0.9, ox: 0.3 } },
  C7_12: { id: "C7_12", text_en: "Facial contours look lower when viewed from the side", category: 7, weights: { aging: 0.8 } },
  C7_13: { id: "C7_13", text_en: "Skin feels loose or lacks resistance when pinched gently", category: 7, weights: { aging: 0.8, bar: 0.2 } },
  C7_14: { id: "C7_14", text_en: "A second chin appears when looking downward", category: 7, weights: { aging: 0.7 } },
  C7_15: { id: "C7_15", text_en: "Forehead lines have become deeper", category: 7, weights: { aging: 0.7 } },

  // Category 8 — Barrier & Recovery
  C8_01: { id: "C8_01", text_en: "All products suddenly feel irritating", category: 8, weights: { bar: 0.9, sen: 0.7 } },
  C8_02: { id: "C8_02", text_en: "Skin has become generally more reactive recently", category: 8, weights: { bar: 0.7, sen: 0.8 } },
  C8_03: { id: "C8_03", text_en: "Redness, dryness and breakouts appear at the same time", category: 8, weights: { bar: 0.9, sen: 0.6, hyd: 0.5, acne: 0.4 } },
  C8_04: { id: "C8_04", text_en: "Changing products caused a significant skin reaction", category: 8, weights: { bar: 0.8, sen: 0.7 } },
  C8_05: { id: "C8_05", text_en: "Skin remains unstable and doesn't settle", category: 8, weights: { bar: 0.8, sen: 0.6 } },
  C8_06: { id: "C8_06", text_en: "Skin takes a long time to recover after exfoliation", category: 8, weights: { bar: 0.8, sen: 0.4 } },
  C8_07: { id: "C8_07", text_en: "Skin became reactive after a laser or peel treatment", category: 8, weights: { bar: 0.7, sen: 0.6 } },
  C8_08: { id: "C8_08", text_en: "Skin barrier feels weakened", category: 8, weights: { bar: 0.9 } },
  C8_09: { id: "C8_09", text_en: "Very minor stimuli trigger a reaction", category: 8, weights: { sen: 0.8, bar: 0.7 } },
  C8_10: { id: "C8_10", text_en: "Skin cannot retain moisture", category: 8, weights: { bar: 0.7, hyd: 0.6 } },
  C8_11: { id: "C8_11", text_en: "Skin heats up quickly and easily", category: 8, weights: { sen: 0.7, bar: 0.5 } },
  C8_12: { id: "C8_12", text_en: "Physical exfoliation or massage has been performed frequently", category: 8, weights: { bar: 0.8, sen: 0.4 } },
  C8_13: { id: "C8_13", text_en: "4 or more moisturising steps are needed to feel comfortable", category: 8, weights: { bar: 0.6, hyd: 0.5 } },
  C8_14: { id: "C8_14", text_en: "Products absorb poorly", category: 8, weights: { bar: 0.7, texture: 0.4 } },
  C8_15: { id: "C8_15", text_en: "Skin feels tight or dry within 30 seconds of cleansing", category: 8, weights: { bar: 1.0, hyd: 0.7 } },
};

export const CATEGORY_INFO: Record<number, { emoji: string; name: string; clinical: string }> = {
  1: { emoji: "🔴", name: "Breakouts & Acne", clinical: "Indicators of sebum dysregulation and follicular inflammation" },
  2: { emoji: "🟡", name: "Oiliness & Makeup Wear", clinical: "Sebum overproduction and its effect on cosmetic stability" },
  3: { emoji: "🔵", name: "Dryness & Dehydration", clinical: "Transepidermal water loss and NMF depletion patterns" },
  4: { emoji: "🟠", name: "Sensitivity & Redness", clinical: "Neurogenic inflammation, vascular hyperreactivity, and impaired tolerance" },
  5: { emoji: "🟤", name: "Pigmentation & Skintone", clinical: "Melanocyte hyperactivation, oxidative stress, and photodamage patterns" },
  6: { emoji: "⚪", name: "Pores & Texture", clinical: "Follicular dilation, keratinisation disorder, and surface irregularity" },
  7: { emoji: "🔷", name: "Wrinkles & Firmness", clinical: "Collagen loss, ECM degradation, and gravitational tissue changes" },
  8: { emoji: "⚠️", name: "Barrier & Recovery", clinical: "Stratum corneum integrity, recovery capacity, and sensitisation state" },
};

export const META_QUESTIONS: MetaQuestion[] = [
  {
    id: "flush_30min",
    text_en: "Does flushing persist for more than 30 minutes?",
    type: "boolean",
    trigger_after_category: 4,
    trigger_condition: (s) => (s["C4_09"] ?? 0) >= 2 || (s["C4_15"] ?? 0) >= 2,
  },
  {
    id: "central_face",
    text_en: "Is redness concentrated on the central face (nose, cheeks)?",
    type: "boolean",
    trigger_after_category: 4,
    trigger_condition: (s) => (s["C4_09"] ?? 0) >= 2 || (s["C4_15"] ?? 0) >= 2,
  },
  {
    id: "exfoliation_2w",
    text_en: "How frequently have you exfoliated in the past 2 weeks?",
    type: "severity",
    trigger_after_category: 8,
    trigger_condition: (s) => (s["C8_12"] ?? 0) >= 2 || (s["C8_06"] ?? 0) >= 2 || (s["C8_15"] ?? 0) >= 2,
  },
  {
    id: "new_actives",
    text_en: "Have you introduced new active ingredients recently?",
    type: "boolean",
    trigger_after_category: 8,
    trigger_condition: (s) => (s["C8_12"] ?? 0) >= 2 || (s["C8_06"] ?? 0) >= 2 || (s["C8_15"] ?? 0) >= 2,
  },
  {
    id: "premenstrual_7_10d",
    text_en: "Do breakouts appear 7–10 days before menstruation?",
    type: "severity",
    trigger_after_category: 1,
    trigger_condition: (s) => (s["C1_02"] ?? 0) >= 2 || (s["C1_03"] ?? 0) >= 2,
  },
  {
    id: "jaw_focus",
    text_en: "Are breakouts specifically concentrated along the jawline?",
    type: "severity",
    trigger_after_category: 1,
    trigger_condition: (s) => (s["C1_02"] ?? 0) >= 2 || (s["C1_03"] ?? 0) >= 2,
  },
];

export const CONTEXT_MODIFIERS: Record<ContextKey, Partial<Record<AxisKey, number>>> = {
  shaving: { sen: 0.15, bar: 0.10, acne: 0.10 },
  makeup: { makeup_stability: 0.20, seb: 0.10 },
  hormonal: { acne: 0.20, seb: 0.15, sen: 0.10 },
  outdoor_work: { ox: 0.25, pigment: 0.15 },
  skincare_beginner: { bar: 0.10, sen: 0.05 },
  recent_procedure: { bar: 0.20, sen: 0.20 },
  low_water_intake: { hyd: 0.15 },
};

export const SKIN_TYPE_BASELINES: Record<SkinType, Partial<Record<AxisKey, number>>> = {
  dry: { hyd: 15, bar: 10, sen: 5 },
  oily: { seb: 20, acne: 10, texture: 10, makeup_stability: 10 },
  combination: { seb: 10, hyd: 8, texture: 8, makeup_stability: 8 },
  sensitive: { sen: 20, bar: 15 },
  normal: {},
};

export const HIGH_RISK_PATTERNS: RiskPattern[] = [
  {
    id: "PATTERN_BARRIER_TRIAD",
    name_en: "Compromised Barrier Triad",
    required: ["C8_03", "C8_01"],
    optional: ["C4_14", "C3_02", "C8_08", "C8_15"],
    min_optional: 2,
    axis_gates: { bar: 50 },
    clinical_en: "Simultaneous redness, dryness and breakouts signal Sensitized Skin Syndrome — ceramide depletion combined with neurogenic inflammation. Barrier-first protocol essential.",
    flag: "BARRIER_EMERGENCY",
    urgency: "CRITICAL",
    threshold: 65,
  },
  {
    id: "PATTERN_HORMONAL_ACNE",
    name_en: "Hormonal Acne Cascade",
    required: ["C1_03", "C1_02"],
    optional: ["C1_07", "C1_08", "C1_12", "C1_15"],
    min_optional: 2,
    axis_gates: { acne: 40 },
    clinical_en: "Cyclical acne on jaw, cheeks and forehead with nodular/cystic lesions indicates androgen receptor hyperactivation. Niacinamide + sebum-control protocol recommended.",
    flag: "HORMONAL_ACNE_PROTOCOL",
    urgency: "HIGH",
    threshold: 70,
  },
  {
    id: "PATTERN_DEHYDRATED_OILY",
    name_en: "Dehydrated Oily Skin Pattern",
    required: ["C2_07", "C2_01"],
    optional: ["C3_01", "C2_14", "C6_04", "C1_11"],
    min_optional: 2,
    axis_gates: {},
    clinical_en: "Oily surface with dry underneath indicates concurrent sebum hypersecretion and stratum corneum dehydration. Hydration-first, then sebum regulation protocol.",
    flag: "HYDRATION_FIRST",
    urgency: "MEDIUM",
    threshold: 75,
  },
  {
    id: "PATTERN_PHOTOAGING",
    name_en: "Photo-Oxidative Aging Pattern",
    required: ["C5_06", "C5_13"],
    optional: ["C7_11", "C7_03", "C5_02", "C5_15"],
    min_optional: 2,
    axis_gates: { ox: 40 },
    clinical_en: "Rapid post-UV pigmentation with increasing melasma indicates accelerated photoaging. Vitamin C + Retinal + Physical SPF50+ essential.",
    flag: "ANTIOXIDANT_PRIORITY",
    urgency: "HIGH",
    threshold: 70,
  },
  {
    id: "PATTERN_COUPEROSE",
    name_en: "Couperose / Vascular Hyperreactivity",
    required: ["C4_15", "C4_09"],
    optional: ["C4_01", "C4_08", "C4_07", "C4_02"],
    min_optional: 2,
    axis_gates: { sen: 45 },
    clinical_en: "Visible capillaries with persistent flushing signal Couperose or early Rosacea Type I. Avoid thermal triggers, alcohol, fragrance. Niacinamide + Azelaic acid protocol recommended.",
    flag: "ANTI_REDNESS_PROTOCOL",
    urgency: "HIGH",
    threshold: 70,
  },
  {
    id: "PATTERN_SEVERE_ACNE",
    name_en: "Severe Inflammatory Acne",
    required: ["C1_07", "C1_08"],
    optional: ["C1_01", "C1_03", "C1_15", "C1_12"],
    min_optional: 2,
    axis_gates: { acne: 50 },
    clinical_en: "Concurrent nodular and pustular acne = IGA Grade 3+. Dermatologist consultation strongly advised. BHA + Niacinamide routine as adjunct therapy.",
    flag: "DERMATOLOGIST_REFERRAL",
    urgency: "CRITICAL",
    threshold: 65,
  },
  {
    id: "PATTERN_AGING_TRIAD",
    name_en: "Accelerated Aging Triad",
    required: ["C7_06", "C7_11"],
    optional: ["C7_03", "C7_07", "C7_12", "C7_14", "C5_13"],
    min_optional: 3,
    axis_gates: { aging: 45 },
    clinical_en: "Combined elasticity loss, deep wrinkles and sagging signal accelerated collagen decline and ECM degradation. 4-step anti-aging: Retinal + Peptide + Collagen booster + Vitamin C.",
    flag: "DEVICE_RECOMMENDED",
    urgency: "HIGH",
    threshold: 70,
  },
  {
    id: "PATTERN_OVER_EXFOLIATION",
    name_en: "Over-Exfoliation Syndrome",
    required: ["C8_12", "C8_06"],
    optional: ["C8_01", "C8_04", "C4_04", "C4_05"],
    min_optional: 2,
    axis_gates: { bar: 50 },
    clinical_en: "Repeated physical exfoliation with impaired recovery indicates stratum corneum over-damage. Stop all active ingredients. Ceramide + Panthenol barrier-rebuild protocol. Minimum 4 weeks stabilization required.",
    flag: "ACTIVE_INGREDIENT_PAUSE",
    urgency: "CRITICAL",
    threshold: 65,
  },
];

export const PRODUCT_CATALOG: Record<string, Product> = {
  biplain_cleanser: { id: "biplain_cleanser", name: "B'Plain Green Bean Foam Cleanser", brand: "B'Plain", phase: "Phase1", type: "Sensitive Cleanser", price_eur: 18, tier: ["Entry", "Full", "Premium"], shopify_handle: "biplain-greenbean-foam-cleanser", key_ingredients: ["Green Bean Extract", "Amino Acid Surfactant", "pH5.5"], target_axes: ["sen", "bar"], for_skin: ["sensitive", "dry", "normal"] },
  drg_cleanser_oily: { id: "drg_cleanser_oily", name: "Dr.G pH Balancing Cleanser", brand: "Dr.G", phase: "Phase1", type: "Oily Skin Cleanser", price_eur: 16, tier: ["Entry", "Full", "Premium"], shopify_handle: "drg-ph-balancing-cleanser", key_ingredients: ["Salicylic Acid", "5-Biome", "8x Hyaluronic Acid", "pH5.5"], target_axes: ["seb", "acne", "texture"], for_skin: ["oily", "combination"] },
  torriden_serum: { id: "torriden_serum", name: "Torriden DIVE-IN Hyaluronic Acid Serum", brand: "Torriden", phase: "Phase2A", type: "Hydration Serum", price_eur: 22, tier: ["Full", "Premium"], shopify_handle: "torriden-dive-in-low-molecular-hyaluronic-acid-serum", key_ingredients: ["5 Types Hyaluronic Acid", "Panthenol", "Alcohol-Free"], target_axes: ["hyd", "bar"], for_skin: ["dry", "combination", "sensitive", "normal"] },
  snature_toner: { id: "snature_toner", name: "S.NATURE Aqua Oasis Toner", brand: "S.NATURE", phase: "Phase2A", type: "Hydration Toner", price_eur: 14, tier: ["Entry"], shopify_handle: "snature-aqua-oasis-toner", key_ingredients: ["Hyaluronic Acid", "Panthenol", "Alcohol-Free"], target_axes: ["hyd"], for_skin: ["all"] },
  aestura_cream: { id: "aestura_cream", name: "Aestura AtoBarrier365 Cream", brand: "Aestura", phase: "Phase2B", type: "Barrier Cream", price_eur: 38, tier: ["Full", "Premium"], shopify_handle: "aestura-atobarrier365-cream", key_ingredients: ["Ceramide NP", "Squalane", "Cholesterol", "Panthenol"], target_axes: ["bar", "hyd", "sen"], for_skin: ["sensitive", "dry", "combination"] },
  snature_squalane: { id: "snature_squalane", name: "S.NATURE Aqua Squalane Serum", brand: "S.NATURE", phase: "Phase2B", type: "Squalane Serum", price_eur: 20, tier: ["Entry", "Full"], shopify_handle: "snature-aqua-squalane-serum", key_ingredients: ["Squalane", "Panthenol", "Allantoin"], target_axes: ["bar", "hyd"], for_skin: ["all"] },
  manyo_bifida: { id: "manyo_bifida", name: "Manyo Bifida Biome Complex Ampoule", brand: "Manyo Factory", phase: "Phase2C", type: "Microbiome Ampoule", price_eur: 32, tier: ["Full", "Premium"], shopify_handle: "manyo-bifida-biome-complex-ampoule", key_ingredients: ["Bifida Ferment Lysate", "10x Hyaluronic Acid", "Madecassoside"], target_axes: ["bar", "sen", "hyd"], for_skin: ["sensitive", "dry", "combination"] },
  bioheal_probioderm: { id: "bioheal_probioderm", name: "Bioheal BOH Probioderm Serum", brand: "Bioheal BOH", phase: "Phase2C", type: "Premium Microbiome Serum", price_eur: 42, tier: ["Premium"], shopify_handle: "bioheal-boh-probioderm-collagen-remodeling-serum", key_ingredients: ["Patented Biome Complex", "12 Peptides", "Collagen"], target_axes: ["bar", "sen", "aging"], for_skin: ["all"] },
  cosrx_bha: { id: "cosrx_bha", name: "COSRX BHA Blackhead Power Liquid", brand: "COSRX", phase: "Phase3_Acne", type: "BHA Exfoliator", price_eur: 22, tier: ["Full", "Premium"], shopify_handle: "cosrx-bha-blackhead-power-liquid", key_ingredients: ["Salicylic Acid (BHA)", "Niacinamide"], target_axes: ["acne", "seb", "texture"], for_skin: ["oily", "combination"] },
  bringgreen_teatree: { id: "bringgreen_teatree", name: "Bring Green Tea Tree Cica Toner", brand: "Bring Green", phase: "Phase3_Acne", type: "Soothing Toner", price_eur: 15, tier: ["Entry", "Full"], shopify_handle: "bring-green-teatree-cica-soothing-toner", key_ingredients: ["3x Tea Tree 50%", "Centella", "AHA"], target_axes: ["acne", "sen"], for_skin: ["oily", "combination", "sensitive"] },
  missha_vitac: { id: "missha_vitac", name: "MISSHA Vita C Plus Ampoule", brand: "MISSHA", phase: "Phase3_Pigment", type: "Brightening Ampoule", price_eur: 35, tier: ["Full", "Premium"], shopify_handle: "missha-vita-c-plus-spot-correcting-and-firming-ampoule", key_ingredients: ["Vitamin C", "Tranexamic Acid", "Niacinamide"], target_axes: ["pigment", "ox", "aging"], for_skin: ["all"] },
  cellfusionc_toning: { id: "cellfusionc_toning", name: "Cell Fusion C Toning C Serum", brand: "Cell Fusion C", phase: "Phase3_Pigment", type: "Vitamin C Serum", price_eur: 38, tier: ["Premium"], shopify_handle: "cell-fusion-c-toning-c-dark-spot-serum", key_ingredients: ["Pure Vitamin C", "Brightening Complex"], target_axes: ["pigment", "ox"], for_skin: ["all"] },
  iope_retinol: { id: "iope_retinol", name: "IOPE Retinol Super Bounce Serum", brand: "IOPE", phase: "Phase3_Aging", type: "Retinol Serum", price_eur: 52, tier: ["Full", "Premium"], shopify_handle: "iope-retinol-super-bounce-serum", key_ingredients: ["Retinal", "Peptides", "Hyaluronic Acid"], target_axes: ["aging", "texture"], for_skin: ["all"] },
  bioheal_collagen: { id: "bioheal_collagen", name: "Bioheal BOH Collagen Intensive Serum", brand: "Bioheal BOH", phase: "Phase3_Aging", type: "Collagen Peptide Serum", price_eur: 45, tier: ["Premium"], shopify_handle: "bioheal-boh-probioderm-collagen-remodeling-intensive-serum", key_ingredients: ["Collagen T1&T3", "12 Peptides", "Biome Complex"], target_axes: ["aging", "bar", "texture"], for_skin: ["all"] },
  drg_soothing_cream: { id: "drg_soothing_cream", name: "Dr.G Red Blemish Soothing Cream", brand: "Dr.G", phase: "Phase4", type: "Gel Cream (Oily)", price_eur: 20, tier: ["Entry", "Full", "Premium"], shopify_handle: "drg-red-blemish-clear-soothing-cream", key_ingredients: ["Madecassoside", "Panthenol", "Aloe"], target_axes: ["acne", "sen", "bar"], for_skin: ["oily", "combination"] },
  snature_moistcream: { id: "snature_moistcream", name: "S.NATURE Aqua Squalane Moisture Cream", brand: "S.NATURE", phase: "Phase4", type: "Moisture Cream", price_eur: 25, tier: ["Full", "Premium"], shopify_handle: "snature-aqua-squalane-moisture-cream", key_ingredients: ["Squalane", "Hyaluronic Acid", "Panthenol"], target_axes: ["hyd", "bar"], for_skin: ["dry", "combination", "normal"] },
  cellfusionc_sunscreen: { id: "cellfusionc_sunscreen", name: "Cell Fusion C Laser Sunscreen 100", brand: "Cell Fusion C", phase: "Phase5", type: "Hybrid Sunscreen", price_eur: 32, tier: ["Full", "Premium"], shopify_handle: "cell-fusion-c-laser-sunscreen-100-spf50", key_ingredients: ["SPF50+/PA++++", "PDRN", "Hybrid UV Filter"], target_axes: ["ox", "pigment", "sen"], for_skin: ["all"] },
  drg_sunscreen: { id: "drg_sunscreen", name: "Dr.G Green Mild Up Sun Plus", brand: "Dr.G", phase: "Phase5", type: "Mineral Sunscreen", price_eur: 20, tier: ["Entry"], shopify_handle: "drg-green-mild-up-sun-plus-spf50", key_ingredients: ["SPF50+/PA++++", "Mineral Filter", "Green Tea"], target_axes: ["ox", "sen"], for_skin: ["all"] },
  medicube_booster: { id: "medicube_booster", name: "Medicube AGE-R Booster Pro", brand: "Medicube", phase: "Device", type: "EMS+LED Device", price_eur: 380, tier: ["Premium"], shopify_handle: "medicube-age-r-booster-pro-ems-device", key_ingredients: ["EMS", "Microcurrent", "LED Phototherapy"], target_axes: ["aging", "texture", "bar"], for_skin: ["all"] },
  mamicare_device: { id: "mamicare_device", name: "Mamicare Home LED Device", brand: "Mamicare", phase: "Device", type: "LED Device", price_eur: 89, tier: ["Full"], shopify_handle: "mamicare-homecare-led-device", key_ingredients: ["Blue LED (Acne)", "Red LED (Regeneration)"], target_axes: ["acne", "aging", "bar"], for_skin: ["all"] },
};
